### ISSUE TITLE
[Git Action] Build with Jekyll Failed

### ISSUE THREAD

**Issue by cha2hyun** [just-the-docs/just-the-docs-template#3]
1. Click "use this template" 
2. create new repo
3. Action said below

<img width="2910" alt="image" src="https://user-images.githubusercontent.com/56015532/190992732-73eaf158-6e0d-404b-9d8f-d07164127a96.png">

```Shell
Run actions/jekyll-build-pages@v1
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv104_0cff86 --label 817f70 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cha2hyun.github.io/cha2hyun.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.4
/usr/local/bundle/gems/jekyll-3.[9](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:10).2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The just-the-docs theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:3[11](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:12):in `to_specs': Could not find 'just-the-docs' (>= 0) among 148 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:[12](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:13):in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:[19](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:20):in `program'
	from /usr/local/bundle/gems/github-pages-[22](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:23)7/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
             Theme: just-the-docs
github-pages 2[27](https://github.com/cha2hyun/cha2hyun.github.io/actions/runs/3081451418/jobs/4980010328#step:4:28) | Error:  The just-the-docs theme could not be found.
```

Any help ?

**Comment by cha2hyun** [comment]
Add cpature image in workflow
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/56015532/190993447-97fcdc64-d480-496a-b73b-c16ca1b56209.png">

**Comment by mattxwang** [comment]
Hi @cha2hyun, sorry for getting back to you late - didn't realize that I don't have notifs on for this repo.

Are you still encountering this problem? If so, could you link me to the repo + action that failed specifically? I can't reproduce this issue locally (i.e. I've clicked "use a template", and it works).

(looking at the log - I'm a bit confused, in that it seems like it's using Jekyll 3.9; that's inconsistent with what's in this repo, which pins to Jekyll 4)

**Comment by olgarithms** [comment]
Hi, I just created a repo from the template and am having the build of the Initial Commit failing.

The logs do not reveal too much...

```
Run actions/configure-pages@v1
  with:
    token: ***
    enablement: true
Warning: Get Pages site failed
Error: Create Pages site failed
Error: AxiosError: Request failed with status code 40[3](https://github.com/olgarithms/test-just-the-docs/actions/runs/3300520998/jobs/5445142817#step:4:3)
```

[[link to failed action](https://github.com/olgarithms/test-just-the-docs/actions/runs/3300520998/jobs/5445142817#step:4:8)]

**Comment by mattxwang** [comment]
Hi @olgarithms,

Thanks for adding on. Hm, This doesn't seem like it's a problem with our theme, but with your use of the action itself. Do you want to try:

- re-running the action
- double-checking that you've enabled GitHub Pages for your repo - you'll want to select the "deploy from actions" option
- making sure you have the right auth, etc. (not sure how this would get misconfigured)

**Comment by olgarithms** [comment]
Ah, true, I hadn't enabled GitHub Pages for the repo (even though I am sure I had checked that...) and now it works fine! Maybe a note in the template README would help? Happy to do it, too!

**Comment by mattxwang** [comment]
> Ah, true, I hadn't enabled GitHub Pages for the repo (even though I am sure I had checked that...) and now it works fine! Maybe a note in the template README would help? Happy to do it, too!

Feel free to submit a PR! If you found it confusing - I'm sure many other people did too. I think it would be helpful!

**Comment by cha2hyun** [comment]
Thanks alot 👍

**Comment by mattxwang** [comment]
@indiVar0508 the problem is that your action assumes the `Gemfile` is top-level, but it's in the `docs` folder. You need to have your workflow go into that folder.
